Proposals/xgov-9.md

AWallet is [first open source](https://forum.algorand.org/t/algorand-wallet-open-source/3497) Algorand wallet. Wallet allows multisig features, ledger powered accounts, rekeying, making account online and protect algorand network, vanity account generation, ARC14 support, contains algorand native payment gateway, and more. AWallet is built as docker image so that anybody can run it locally in their environment and debug for example sandbox accounts. 
We hope to continue to add more features.
With this ARC43 request we seek feedback on the product and possibly the help by community. The AWallet was built by community and is meant to be for Algorand community.

xGov-9 - AWallet

---

Proposals/xgov-39.md
Proposals/xgov-41.md

A draft proposal. I had some problems with the validator and external links, please see [this issue](https://github.com/algorandfoundation/xGov/issues/40) for discussion.
Edit: my issues are cleared up, thanks! I am fixing them.
Thanks!

xGov-41: minthol, the next-gen loyalty program platform

---

Proposals/xgov-82.md

We will host at least 6 algorand meetups through the year 2024 and improve algorand awareness in the area.

xgov-82: Prague community meetups

---

Proposals/xgov-79.md

With this grant request we will implement source code management by DAO onchain decision making at github.

XGov79: VoteCoin - GitHub tools

---

Proposals/xgov-x.md

The ASA Stats team will develop and deploy endpoints that will be used for creating CSV files ready to be imported into crypto tax software.

xGov-71: Milestone 2 - ASA Stats tax reporting reference

---

Proposals/xgov-70.md
Proposals/xgov-x.md

ASA Stats API brings all the functionalities of the ASA Stats website to the third-party developers.

xGov-70: Securing ASA Stats API high availability for the next 2 years

---

Proposals/xgov-165.md
Proposals/xgov-x.md

Thank you for considering our proposal!

xGov 165: Proposal to build NFT Bridge between Algorand and EVM based networks

---

Proposals/xgov-154.md

Cosmic Champs partnering with legendary indie toy company to bring physical toys in-game on Algorand

xGov-154: Cosmic Champs partnering with legendary indie toy company to bring physical toys in-game on Algorand

---

Proposals/xgov-152.md

Increase server fleet capabilities for our game to meet increasing demand and ensure flawless experience for new users prior to the bull run and mass adoption. Good games == Algo is good for gaming

xGov-152: Algorand is THE chain for Gaming (establishing the RWA narrative)

---

Proposals/xgov-150.md
Proposals/xgov-94.md

Thank you for considering this proposal for cross-chain activities to boost the algorand eccosystem.

xGov -150 - Cross-Chain community promotion and collaberation

---

Proposals/xgov-142.md
Proposals/xgov-x.md

Thank you for reviewing the proposal.

xGov-142: Composable Marketplace by Asalytic

---

Proposals/xgov-141.md
Proposals/xgov-x.md

The second milestone of the xGov #70 proposal that has passed in the Voting Session 2.

xGov-141: Securing ASA Stats API high availability for the next 2 years (Milestone 2)

---

Proposals/xgov-121.md
Proposals/xgov-x.md

Thank you for considering our proposal.

xGov-121: The Next Block Proposal to Expand on Algorand Marketing and Relevant Content 

---

Proposals/xgov-118.md

Just adding the abstract, will be adding more this week until deadline.

xgov-118.md pressdot - The First WebMarket

---

Proposals/xgov-114.md

Easily Claim and Create Atomic Swap with this new tool for The Laboratory (formerly Evil Tools)

xgov-114 - Thurstober Claims - Easily Create and Claim Atomic Swaps

---

Proposals/xgov-112.md

We're back! In this proposal we want to add in NFD Vault Support to reduce the opt-friction for new Algorand Users, Add ARC-36 Support (Non-Rarity Filters) to our Simple Mint and Update Tools, Add in advanced asset tools to change the Manager, Freeze, and Clawback Address, and add in a tool where you can enter a Wallet Address to download the tx history. In addition we plan on updating the site with a redesign.

xgov-112 - Thurstober Tools - Onboarding Enhancements, Upgrades, and Redesign

---

Proposals/xgov-98.md
Proposals/xgov-x.md

Thanks for taking the time to review the Nimblr proposal. We look forward to building with you.

xGov-98 - Launch of Nimblr: Audits, Licensing, Go Live

---

Proposals/xgov-171.md
Proposals/xgov-202.md

Request for retroactive funding to open source pactfi stableswaps

xgov-202 Pact.fi Retroactive Stableswaps

---

Proposals/xGov180.md

xGov-181-Research Article on Algorand Voting Technologies

---

Proposals/xgov-198.md

xGov-198 - CompX - Auto-Compounding Farms

---

Council/xgov_council-218.md

First draft of xGov application

Wilder_Stubbs_xgov_council-2.md

---

Council/xgov_council-222.md
Council/xgov_council-4.md

xgov_council-222.md

---

Council/xgov_council-18.md
Council/xgov_council-19.md

Hi folks, creating a PR for my application. Thank you for your consideration.

Application for xGov Council  - Sean Fraser xgov_council-19

---

Council/xgov_council-24.md

- Application for a seat on the xGov council (Michael T Chuang)

Create xgov_council-24.md (michaeltchuang) 

---

Council/xgov_council-1.md
Council/xgov_council-10.md
Council/xgov_council-11.md
Council/xgov_council-12.md
Council/xgov_council-14.md
Council/xgov_council-15.md
Council/xgov_council-16.md
Council/xgov_council-18.md
Council/xgov_council-19.md
Council/xgov_council-2.md
Council/xgov_council-20.md
Council/xgov_council-21.md
Council/xgov_council-22.md
Council/xgov_council-23.md
Council/xgov_council-24.md
Council/xgov_council-3.md
Council/xgov_council-4.md
Council/xgov_council-5.md
Council/xgov_council-6.md
Council/xgov_council-7.md
Council/xgov_council-8.md
Council/xgov_council-9.md

The elected councillors are:
Simon Belingar [@simonb](https://forum.algorand.co/u/simonb)
Patrick Bennett [@PatrickB](https://forum.algorand.co/u/patrickb)
Paweł Pierścionek [@urtho](https://forum.algorand.co/u/urtho)
Dr. Uroš Hudomalj [@uhudo](https://forum.algorand.co/u/uhudo)
Mohamed Ghiasi [@emg110](https://forum.algorand.co/u/emg110)
Michael T Chuang
Kieran Nelson [@Xxiled](https://forum.algorand.co/u/xxiled)
Robbie Baxter [@fifth.race](https://forum.algorand.co/u/fifth.race)
Paul Hinrichsen [@Conscious](https://forum.algorand.co/u/conscious)
Naoki Yamamoto [@aper_nft](https://forum.algorand.co/u/aper_nft)
John Mizzoni [@fisherman.algo](https://forum.algorand.co/u/fisherman.algo)

xGov Council 2025 - Official Election Results
